name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install deps
        run: |
          pip install flake8 black isort mypy pytest
          pip install fastapi sqlalchemy uvicorn pytest httpx

      - name: flake8
        run: flake8 .

      - name: black
        run: black --check .

      - name: isort
        run: isort --check-only .

      - name: mypy
        run: mypy .

      - name: pytest
        run: pytest
